### ISSUE TITLE
Fallback image upload breaks plugin

### ISSUE THREAD

**Issue by JoeRathbun** [azurecurve/azrcrv-add-open-graph-tags#1]
code_Potent suggested I file an issue here, I have done nothing here before, but I'll give it a shot.

I have been testing version 1.3.4. as I said on the classicpress forum, it was working great but didn't send the featured image.

So I tried to upload a fallback image to see if it would send that. when I "saved" the settings page went to blank grey, fortunately I still had the rest of the backend/dashboard so I could deactivate.

Before I deactivated, I tried to go to a post on the front end and the pages were blank again, so I believe that possibly it was the fallback image recorded in the database? that killed the front end when I first upgraded to v1.3.3?

I don't know if I am opening an issue correctly, but there it is.
RandyC

**Comment by JoeRathbun** [comment]
I realized that when I was changing settings on the plugin, while adding a fallback image, that I clicked the box for "Floating Featured Images" even though I had no idea what it was.

This morning I deleted the deactivated plugin (v1.3.4) and reinstalled it and reactivated, as soon as I did, the front end went blank again, so I deactivated.

ClassicPress 1.2.0 running “Mission News” theme.
Running PHP version: 7.0.33

**Comment by azurecurve** [comment]
I'v gotthe plugin changed to use the featured image for the open graph tags.

I'll do some testing over the weekend and see if I can reproduce the error you're seeing, which I haven't been able to so far.

I'll test with the Mission News theme; it is also possible that there might be a plugin conflict. Are you able to share a list of active plugins?

**Comment by JoeRathbun** [comment]
Version 1.4.0 solved all issues
